### ISSUE TITLE
mixed 옵션에 대한 건의

### ISSUE THREAD

**Issue by roeniss** [devHudi/kr-numbers#2]
한국은 보통 숫자를 네 자리씩 끊어서 읽는데 (1억 2345만 6789)

제시해주신 readme의 예시 마지막에선 "35만 2,043"라는 표현이 나와있습니다. 이에 다음 두 가지 옵션을 생각해보았습니다.

1) mixed일 경우엔 별도의 콤마 없이 표기 (ex. mixed=true & 99999999999 ---> 999억9999만9999)

2) mixed와 별도로, 콤마 기능 추가 (ex. mixed=true, comma=3 (default = -1) & 99999999999 --> 999억 9,999만 9,999)

**Comment by devHudi** [comment]
사실 초기에는 말씀해주신 내용 그대로 `comma` 라는 옵션을 따로 둬 **mixed=true** 일 경우 `comma` 여부에 따라 콤마 유무를 결정했었습니다. 다만, `comma` 가 true 여도 `mixed` 가 false 라면 `comma` 옵션은 무시되는 문제 때문에 `mixed` 옵션에 기본적으로 콤마를 붙이게 되었습니다. 말씀드린 문제가 존재해도 사용상에 큰 문제가 없다면, 저도 `comma` 옵션이 있는 것이 좀 더 좋아보입니다.

**Comment by roeniss** [comment]
2x2 조합(comma & mixed on/off) 에 대한 각각의 결과를 반환하는 function이 있으면 어떨까 싶네요 :)

**Comment by devHudi** [comment]
더 자세히 설명해주실 수 있을까요?

**Comment by roeniss** [comment]
```js
if (mixed && comma !== -1){ // 쓰면서 알았는데 그냥 0이 default인게 맞는 것 같네요... 위쪽 코멘트에 예시로 -1을 써놨기 때문에 그냥 -1로 코드를 써볼게요
   return "999억 9,999만 9,999" // comma ===3 일 경우임 
} else if (mixed && comma === -1){
  return "999억9999만9999"
} else if (!mixed && comma !== -1){
  return new Error("you muse enable 'mixed' option")
  // 또는, comma만 있어도 mixed = true로 간주하고 return "999억9999만9999"
} else { // if (!mixed && comma === -1)
  return "구백구십구억구천구백구십구만구천구백구십구"
}
```
